# Generated by Django 4.2.9 on 2024-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(choices=[('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL1.jpg', 1), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL2.jpg', 2), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL3.jpg', 3), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL4.jpg', 4), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL5.jpg', 5), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL6.jpg', 6), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL7.jpg', 7), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL8.jpg', 8), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL9.jpg', 9), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL10.jpg', 10), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/DL11.jpg', 11)], default='https://dislodged.s3.ap-northeast-2.amazonaws.com/DL1.jpg', max_length=128),
        ),
    ]
