# Generated by Django 4.2.9 on 2024-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_like_delete_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(choices=[('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+0.png', 1), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+1.png', 2), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+2.png', 3), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+3.png', 4), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+4.png', 5), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+5.png', 6), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+6.png', 7), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+7.png', 8), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+8.png', 9), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+9.png', 10), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+10.png', 11), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+11.png', 12), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+12.png', 13), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+13.png', 14), ('https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+14.png', 15)], default='https://dislodged.s3.ap-northeast-2.amazonaws.com/image/Frame+0.png', max_length=128),
        ),
    ]
