# Generated by Django 4.2.9 on 2024-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_voice_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_info',
            name='pitch',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='voice_info',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='voice_info',
            name='type',
            field=models.TextField(default='ko-KR-Wavenet-D'),
        ),
    ]
