# Generated by Django 4.2.9 on 2024-04-05 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_voice_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_voice', to=settings.AUTH_USER_MODEL),
        ),
    ]
