# Generated by Django 4.2.9 on 2024-03-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_voice_info_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_info',
            name='type',
            field=models.TextField(default='ko-KR-Standard-A'),
        ),
    ]
