# Generated by Django 4.2.9 on 2024-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_voice_info_pitch_alter_voice_info_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_info',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
